#!/usr/bin/env bash
# Install ngnix
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chown -R $USER:$USER /var/www/html/index.html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
